on:
  workflow_dispatch:
  push:
    branches: main

name: quarto-ieee publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R1
        uses: r-lib/actions/setup-r@v2
      - name: Setup R2
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/render@v2